config/routes.rb
Rails.application.routes.draw do
root 'brands#index'
  resources :brands, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brands.rb
class Brands
  # model page for brands. In this app there is no database.It works on models. 
  include ActiveModel::Model

  attr_accessor :id, :name, :products

  @@brands = []
  @@id_counter = 1

  def initialize(attributes = {})
    super(attributes)
    @id = @@id_counter
    @@id_counter += 1
  end

  def self.all
    @@brands
  end

  def self.find(id)
    @@brands.find { |brand| brand.id == id.to_i }
  end

  def save
    @@brands << self
  end

  def update(attributes)
    self.attributes = attributes
  end

  def destroy
    @@brands.delete(self)
  end
end

app/models/products.rb
class Products
    # model page for products.

  include ActiveModel::Model

  attr_accessor :id, :name, :brand_id, :brand

  @@products = []
  @@id_counter = 1

  def initialize(attributes = {})
    super(attributes)
    @id = @@id_counter
    @@id_counter += 1
  end

  def self.all
    @@products
  end

  def self.find(id)
    @@products.find { |product| product.id == id.to_i }
  end

  def save
    @@products << self
  end

  def update(attributes)
    self.attributes = attributes
  end

  def destroy
    @@products.delete(self)
  end
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
# end
class ApplicationController < ActionController::Base
    include Rails.application.routes.url_helpers
  end
  

app/controllers/brands_controller.rb
 class BrandsController < ApplicationController
#  controller page for adding,deleting and editing brands
  def index
    @brands = Brands.all
    @brands.each do |brand|
      brand.products = Products.all.select { |product| product.brand_id == brand.id }
    end
  end

   def new
     @brand = Brands.new
     @brands = Brands.all
     puts @brands.inspect

   end

   def create
     brand_params = params.require(:brands).permit(:name)
     @brand = Brands.new(brand_params)
     @brand.save
     redirect_to brands_path
   end
  
   def edit
     @brand = Brands.find(params[:id])
   end

   def update
     @brand = Brands.find(params[:id])
     @brand.update(brand_params)
     redirect_to brands_path
   end

   def destroy
     @brand = Brands.find(params[:id])
     @brand.destroy
     redirect_to brands_path
  end

   private

   def brand_params
     params.require(:brands).permit(:name)
   end
      def find_brand
     @brand = Brands.find(params[:id])
   end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #  controller page for adding,deleting and editing products. at editing part I did not put an option to change brand.

  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Products.all

  end

  def show
  end

  def new
    @product = Products.new
    @brands = Brands.all
  end


  def create
    product_params = params.require(:products).permit(:name, :brand_id)
    @product = Products.new(product_params)

    brand_id = product_params[:brand_id]
    @product.brand = Brands.find(brand_id) if brand_id.present?

    if @product.save
      redirect_to products_path, notice: "Ürün başarıyla oluşturuldu."
    else
      @brands = Brands.all
      render :new
    end
  end

  def update
    product_params = params.require(:products).permit(:name, :brand_id)

    brand_id = product_params[:brand_id]
    @product.brand = Brands.find(brand_id) if brand_id.present?

    if @product.update(product_params)
      redirect_to products_path, notice: "Ürün başarıyla güncellendi."
    else
      render :edit
    end
  end
  

  def edit
    @brand = Brands.find(params[:id])

  end


  def destroy
    @product.destroy
    redirect_to products_path, notice: "Ürün başarıyla silindi."
  end

  private

  def find_product
    @product = Products.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brands/edit.html.erb
<h1>Edit Brand</h1>
<%= form_for @brand, url: brand_path, method: :put do |f| %>
  <div class="field">
    <%= f.label :name, "Brand Name" %>
    <br> <br>
    <%= f.text_field :name %>
    <br> <br>
    <%= f.submit "Save" %>

  </div>
<% end %>

<%= link_to "Go back", brands_path %>

app/views/brands/index.html.erb

<h1>Brands</h1>
<style>
  .table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
  }

  .table th, .table td {
    padding: 8px;
    border: 1px solid #ccc;
  }

  .table th {
    background-color: #f0f0f0;
    text-align: left;
  }

  .edit-button, .delete-button {
    padding: 6px 12px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    text-decoration: none;
    margin-right: 5px;
  }

  .edit-button:hover, .delete-button:hover {
    background-color: #0056b3;
  }
  .go-products-button {
  display: inline-block;
  padding: 8px 12px;
  background-color: #007bff;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  }

 .go-products-button:hover {
  background-color: #0056b3;
  }
</style>

<table class="table">
  <thead>
    <tr>
      <th>Brand Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand.id),class: 'edit-button' %></td>
<td>
  <%= form_with(model: brand, url: brand_path(brand.id), method: :delete, data: { confirm: 'Emin misiniz?' }) do |form| %>
    <%= form.submit 'Delete', class: 'delete-button' %>
  <% end %>
</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Add New Brand', new_brand_path %>
<br> <br>
<%= link_to 'Go Products', products_path, class: 'go-products-button' %>


app/views/brands/new.html.erb

<h1>Add New Brand</h1>
<%= form_with(model: @brand, url: brands_path, method: :post) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>



app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_with(model: @product, url: product_path, method: :put) do |form| %>
  <%= form.label :name, 'Product Name' %>
  <%= form.text_field :name %>

  <%= form.submit 'Save' %>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>
<style>
  .table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
  }

  .table th, .table td {
    padding: 8px;
    border: 1px solid #ccc;
  }

  .table th {
    background-color: #f0f0f0;
    text-align: left;
  }

  .edit-button, .delete-button {
    padding: 6px 12px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    text-decoration: none;
    margin-right: 5px;
  }

  .edit-button:hover, .delete-button:hover {
    background-color: #0056b3;
  }
</style>
<table class="table">
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Brand</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand.name %></td>
        <td><%= link_to 'Edit', edit_product_path(product.id), class: 'edit-button' %></td>
        <td>
        <%= form_with(model: product, url: product_path(product.id), method: :delete, data: { confirm: 'Emin misiniz?' }) do |form| %>
          <%= form.submit 'Delete', class: 'delete-button' %>
        <% end %>
      </td>      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Add New Product', new_product_path %>

app/views/products/new.html.erb
<style>
  .form-container {
    display: inline-block;
    margin-right: 10px; 
  }

  label {
    display: block; 
    margin-bottom: 5px; 
  }

  .form-wrapper {
    display: inline-block;
    vertical-align: top;
  }

  .link-container {
    margin-top: 10px;
  }
</style>

<h1>Add New Product</h1>

<div class="form-wrapper">
  <%= form_with model: @product, url: products_path do |form| %>
    <div class="form-container">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="form-container">
      <%= form.label :brand_id, "Brand" %>
      <%= form.collection_select :brand_id, Brands.all, :id, :name %>
    </div>
    <div class="actions">
    <br>
      <%= form.submit "Save" %>
    </div>
  <% end %>
</div>

<div class="link-container">
  <%= link_to 'Go Back', products_path %>
</div>